# Subscribes someone to the event
POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Usuário Indicado 3",
  "email": "indicado3@gmail.com",
  "referrer": "dfb9f90b-7c7f-45f2-9d69-0c1975e5069f"
}

###

# Access invite link and redirects user
GET http://localhost:3333/invites/eeff9cce-5c4e-479c-a83e-d61283205cae

###

# Get subscriber invite clicks count
GET http://localhost:3333/subscribers/eeff9cce-5c4e-479c-a83e-d61283205cae/ranking/clicks

###

# Get subscriber invites count
GET http://localhost:3333/subscribers/eeff9cce-5c4e-479c-a83e-d61283205cae/ranking/count

###

# Get subscriber ranking position
GET http://localhost:3333/subscribers/eeff9cce-5c4e-479c-a83e-d61283205cae/ranking/position

###

# Get ranking
GET http://localhost:3333/ranking
